### ISSUE TITLE
Problem with loading and geting mails

### ISSUE THREAD

**Issue by LaShonkilla** [bkaankose/Wino-Mail#516]
I recently set up an IMAP email account, but it's not working properly. Every time I open the mailbox or switch between emails, it starts loading messages from 2023 instead of showing the most recent ones. It takes about 2 minutes for everything to load, and only then do I see a notification that I have 140 new messages. However, I don't receive any notifications on new emails.

**Comment by bkaankose** [comment]
Which imap server are you connected to? If this is a public-free provider, I'd like to test this on myself.

**Comment by LaShonkilla** [comment]
I honestly don't know is it public but I am paying for hosting and having mail on it.

I sent you the video of what is happening and how its working first time is when I opened application and mails started to load from year ago and the second time is when I changed to my second account and went back. 

When I was recording mails didn't even load but usually they start to load again from start when I change accounts.

[Recording 2025-01-17 141707.zip](https://github.com/user-attachments/files/18454918/Recording.2025-01-17.141707.zip)

**Comment by wawrzenczyka** [comment]
I'm just chipping in to mention that I have the exact same problem - loading mail from IMAP account takes several minutes (though it doesn't load sequentially like in the video above). Interrupting that process breaks loading emails on both accounts.

**Comment by bkaankose** [comment]
New beta release 1.9.50.0 has been released yesterday. You go download it in the link below and give it a try.

https://github.com/bkaankose/Wino-Mail/releases/tag/v1.9.50

I believe some of the issues with performance and loading mails has been fixed in this release. You can find the beta installation steps in the [readme](https://github.com/bkaankose/Wino-Mail/blob/main/README.md).

**Comment by wawrzenczyka** [comment]
Thank you for taking the time to look into this issue! Unfortunately, installing this version doesn't fix the problem, see this video below for how swapping between Gmail and IMAP accounts works for me. 

https://github.com/user-attachments/assets/b6d89fe3-7516-4055-bc8e-10a5c2709f73

One more thing that caught my attention is that even though the release is labeled as 1.9.50, the downloaded zip has 1.9.45 in its name - is the package correct?

**Comment by reekotubbs** [comment]
Does the platform store local data snapshots of each account? It seems to pull the information each time an account gains focus. Windows mail does not have this issue, it instantly loads the previous snapshot of data and then attempts to load any new data added since the refocus. This is problematic, because even checking Manage Accounts or Settings causes the data to be repulled once going back to an account or linked accounts. Does the roadmap include these types of improvements?

**Comment by winiak** [comment]
Hi, I just installed Version 1.10.7.0. I'm using commercial IMAP server webd.pl. Every time I start Wino Mail (Windows 10) the list of emails is empty and the application is downloading emails from the serer - 1 by 1, starting from the first email (4 years) - it takes several minutes. The app is configured to Minimize to system tray when closed - and the situation above happens every time I start it either by clicking on a launch icon or by system tray icon.

**Comment by Agredo** [comment]
I am observed the same issue and started a diskussion. 
https://github.com/bkaankose/Wino-Mail/discussions/883

I have a mail box with 16K Mails and its starts to download it every time.
